config_name: test

env:
  num_targets: 10

  num_agents: 3

  sensing_range: 2

  grid_size:
    x: 18
    y: 18
  
  obstacles:
    max_num: 5

  sub_groups:
    side_division: 3
    #group_obstacle_matrix: [[5,5,10],[5,5,10],[10,10,10]]

  