config_name: test

env:
  num_targets: 10

  num_agents: 10

  grid_size:
    x: 18
    y: 18
  
  obstacles:
    max_num: 10

  sub_groups:
    side_division: 3
    group_obstacle_matrix: [[5,5,10],[5,5,10],[10,10,10]]

  