config_name: 20targetPyG

weight_decay: 0.00001
lr: 0.0003
batch_size: 64

initialization:
  type: kaiming


env:
  num_targets: 20
  random_start: True
  num_agents: 4
  comm_range: 8
  grid_size:
    x: &x 18
    y: &y 18
  sub_groups:
    side_division: 3
    group_obstacle_matrix: [[0,0,0],[0,0,0],[0,0,0]]
  vis:
    mode: global&local

agent:
  UAV1:
    type: UAV
    num: 4
    sensing_range: 4
    max_speed: 1
     
network:
  x: *x
  y: *y
  CNNEncoder:
    RES: True
    input_channel: 3
    output_channel: 3
    channel: [3,16,64,16,3]
    kernel_size: [3,3,3,3]
    activation: sigmoid

  Flatten:
    output_feature: 1024
    activation: relu
  
  Fusion:
    model: GAT
    shortcut: True
    K: 2
    heads: 3
    input_feature: [1024,32,32]
    output_feature: [32,16,16]
    activation: relu

  MLP:
    
    output_feature: [48,64,5]
    activation: relu
    

