config_name: 20target_train_6agents

weight_decay: 0.00001
lr: 0.00001
batch_size: 512

loss: weighted
prior: False
preprocess: 
  enable: True
  history: True
  mul: False
initialization:
  type: kaiming

env:
  num_targets: 20
  random_start: True
  num_agents: 3
  comm_range: 6
  grid_size:
    x: &x 15
    y: &y 15
  sub_groups:
    side_division: 3
    group_obstacle_matrix: 
      - [[0,0,0],[0,0,0],[0,0,0]]
      - [[5,5,5],[5,5,5],[5,5,5]]
      - [[0,3,5],[0,3,3],[0,0,3]]
      - [[5,3,0],[3,3,0],[3,0,0]]
      - [[0,0,3],[0,3,3],[0,3,5]]
      - [[3,0,0],[3,3,0],[5,3,0]]
  vis:
    mode: global&local

agent:
  UAV1:
    type: UAV
    num: 3
    sensing_range: 4
    max_speed: 1
  UGV1:
    type: UGV
    num: 3
    sensing_range: 4
    max_speed: 1
     
network:
  x: *x
  y: *y
  
  CNNEncoder:
    RES: False
    input_channel: 3
    output_channel: 3
    channel: []
    kernel_size: []
    activation: relu
    dropout: 0.05
    batch_norm: True

  Flatten:
    activation: relu
  
  Fusion:
    model: GAT
    shortcut: True
    attention_mode: KeyQuery
    K: 1
    heads: 3
    input_feature: [900,16]
    output_feature: [16,225]
    activation: relu

  CNNDecoder:
    
    channel: [7,8,1]
    kernel_size: [3,3]
    activation: relu
    dropout: 0.05
    batch_norm: True
  
  MLP:
    
    output_feature: [225,64,5]
    activation: relu
    dropout: 0.05
    batch_norm: True

  ByPassMLP:

    output_feature: [225,128,1]
    activation: relu
    dropout: 0.05
    batch_norm: True
    

